# Generated by Django 4.1.5 on 2023-04-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_task_options_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k', models.IntegerField()),
                ('n', models.IntegerField()),
                ('lower_bound', models.IntegerField()),
                ('upper_bound', models.IntegerField()),
                ('metrika', models.IntegerField()),
                ('q1', models.CharField(max_length=100)),
                ('q2', models.CharField(max_length=100)),
                ('q3', models.CharField(max_length=100)),
                ('w', models.BinaryField()),
            ],
        ),
    ]
