# Generated by Django 4.1.5 on 2023-06-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_cluster_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='name_data',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
