# Generated by Django 4.1.5 on 2023-06-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_cluster_name_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='clstr_count',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
